name: idb_shim
version: 1.7.2+3
author: Alexandre Roux Tekartik <alex.tekartik.pub@gmail.com>
description: indexed_db dart polyfill over native, websql, file io or memory implementation
homepage: https://github.com/tekartik/idb_shim.dart

environment:
  sdk: '>=2.1.0-dev <3.0.0'

dependencies:
  sembast: '>=1.15.1 <3.0.0'
  collection: '>=1.14.10 <3.0.0'
  path: '>=1.6.1 <3.0.0'
  js: '>=0.6.1 <2.0.0'

dev_dependencies:
  pedantic: '>=1.4.0'
  stack_trace: any
  logging: any
  test: '>=1.2.0'
  dev_test: '>=0.13.0'
  chrome_travis:
    git:
      url: git://github.com/tekartik/chrome_travis.dart
      ref: dart2
    version: '>=0.1.4'
  build_runner: '>=0.9.0'
  build_test: '>=0.10.2'
  build_web_compilers: '>=0.4.0'


dependency_overrides:
  sembast:
    path: ../sembast.dart/sembast