name: idb_shim
version: 1.3.5
author: Alexandre Roux Tekartik <alex.tekartik.pub@gmail.com>
description: indexed_db dart polyfill over native, websql, file io or memory implementation
homepage: http://alextekartik.github.io/idb_shim.dart/
environment:
  sdk: '>=1.13.0 <2.0.0'
dependencies:
  sembast: '>=1.3.1'
  collection: any
dev_dependencies:
  browser: any
  logging: any
  test: any
  dev_test: any
#dependency_overrides:
#  sembast:
#    git: https://github.com/alextekartik/sembast.dart