name: idb_shim
version: 1.6.0
author: Alexandre Roux Tekartik <alex.tekartik.pub@gmail.com>
description: indexed_db dart polyfill over native, websql, file io or memory implementation
homepage: http://alextekartik.github.io/idb_shim.dart/
environment:
  sdk: '>=2.0.0-dev.58 <3.0.0'
dependencies:
  sembast: '>=1.9.0'
  collection: '>=1.14.10'
  path: '>=1.6.1'
  js: '>=0.6.1'
dev_dependencies:
  stack_trace: any
  browser: any
  logging: any
  test: '>=1.2.0'
  dev_test: '>=0.12.0'
  chrome_travis:
    git:
      url: git://github.com/tekartik/chrome_travis.dart
      ref: dart2
    version: '>=0.1.4'
  build_runner: '>=0.9.0'
  build_test: '>=0.10.2'
  build_web_compilers: '>=0.4.0'