name: idb_shim
version: 2.0.0-nullsafety.2
description: indexed_db dart base interface with implementation for native (browser), file (io) and in memory.
homepage: https://github.com/tekartik/idb_shim.dart/tree/master/idb_shim

environment:
  sdk: '>=2.12.0-29.10.beta <3.0.0'

dependencies:
  sembast: '>=3.0.0-nullsafety.2 <3.0.0'
  collection: '>=1.15.0-nullsafety.5 <3.0.0'
  path: '>=1.8.0-nullsafety.3 <3.0.0'
  js: '>=0.6.3-nullsafety.3 <2.0.0'

dev_dependencies:
  pedantic: '>=1.10.0-nullsafety.3'
  pub_semver:
  stack_trace: '>=1.10.0-nullsafety.6'
  logging: '>=0.11.4'
  test: '>=1.16.0-nullsafety.12'
  dev_test: '>=0.13.0'
  process_run: '>=0.10.3'
  build_runner: '>=1.5.0'
  build_test: '>=0.10.2'
  build_web_compilers: '>=0.4.0'
  io:
  yaml:
  # build_vm_compilers: '>=0.1.2'
