name: idb_test
description: idb testing
version: 0.1.1
homepage: https://github.com/tekartik/idb_shim.dart/tree/master/idb_test
author: alex <alex@tekartik.com>
publish_to: none

environment:
  sdk: '>=2.4.0 <3.0.0'
  idb_shim: '>=1.10.3+1 <3.0.0'

dev_dependencies:
  pedantic: '>=1.4.0 <3.0.0'
  process_run: '>=0.10.0+1'
  test:
  build_runner: '>=1.5.0'
  build_test: '>=0.10.2'
  build_web_compilers: '>=0.4.0'

dependency_overrides:
  idb_shim:
    path: ../idb_shim
